### PR TITLE
Update for ember-cli@0.2.0-beta.1 [WIP]

### PR DESCRIPTION
**Pull request by davewasmer**
Update for preprocessor refactor in ember-cli 0.2.0-beta.1. Used kimroen/ember-cli-coffeescript#60 as my guide.

### CODE REVIEW

**Comment by davewasmer** [comment]
This patch appears to fail for nested addons. Investigating ...

**Comment by davewasmer** [comment]
Alright, I this appears to be working, but only after fixing what appears to be a bug in `ember-cli-coffeescript`.

This would have to wait for that PR to be accepted, and require that new version of `ember-cli-coffeescript` as a dependency.

In the meantime - I ended up refactoring how the Coffeescript compile happens. I might have gone a bit overboard though, let me know what you think.

**Comment by alexspeller** [comment]
Hi for some reason notifications of this repo for me were turned off. Looking at this now.

**Comment by davewasmer** [comment]
Ping @rwjblue at his request.

Also, here's [that PR on ember-cli-coffeescript](https://github.com/kimroen/ember-cli-coffeescript/pull/64) I mentioned above.

**Comment by alexspeller** [comment]
Already pulled in code from this as part of a big refactor, thanks!

**Pull request closed without merging**
